### ISSUE TITLE
Type equality from universe member equality

### ISSUE THREAD

**Issue by cangiuli** [RedPRL/sml-redprl#444]
There are apparently no rules for deducing equality of types from an equality of members of a universe. See this goal for an example:

```
  Goal #7375.
    ty/a : (U #l kan)
    ty/b : (U #l kan)
    p : (path [_] (U #l kan) ty/a ty/b)
    a : ty/a
    >> ty/a = (@ p 0) type
```

**Comment by favonia** [comment]
There are, but right now you have to manually internalize it. It is relatively difficult for the auto tactic to decide whether we want to internalize `EQ_TYPE` or not.

**Comment by favonia** [comment]
One possible hack is to implement a duplicate of `Path.EqAppCoonst` for `EQ_TYPE`.

**Comment by favonia** [comment]
This is the function that needs more love: https://github.com/RedPRL/sml-redprl/blob/d036d52b1e374c4bc89295ab542671dd8ca59f10/src/redprl/refiner.fun#L536-L546

**Comment by jonsterling** [comment]
@favonia I didn't realize that there was a way to do this manually... How?

**Comment by favonia** [comment]
@jonsterling Use `let`.

**Comment by jonsterling** [comment]
@favonia Ah, I didn't realize that would work for `EQ_TYPE` goals. Thanks!

**Comment by jonsterling** [comment]
@cangiuli I can show you at some point what @favonia means.

**Comment by cangiuli** [comment]
@jonsterling That would be great, thanks!

I get that `auto` shouldn't always look for an equality in a universe, but I think the most straightforward goals (like the one above) should be solved automatically.

**Comment by jonsterling** [comment]
@cangiuli Yeah... I don't yet know how to make that goal get solved automatically, but I agree it is desirable and even plausible, once we revamp the automation.

**Comment by cangiuli** [comment]
@favonia Am I doing something wrong here?

```
Thm PathToFn(#l:lvl) : [
  (->
   [ty/a ty/b : (U #l kan)]
   [p : (path [_] (U #l kan) ty/a ty/b)]
   (-> ty/a ty/b))
] by [
  unfold Equiv;
  lam ty/a, ty/b, p, a.
    let eq : [(= ty/a (@ p 0) (U #l kan))] = auto.
      `(coe 0~>1 [x] (@ p x) a); auto; ?q
].
```
Then `q` prints three subgoals, the first of which is:
```
  Goal #7474.
    ty/a : (U #l kan)
    ty/b : (U #l kan)
    p : (path [_] (U #l kan) ty/a ty/b)
    a : ty/a
    eq : (= ty/a (@ p 0) (U #l kan))
    >> ty/a = (@ p 0) type
```

**Comment by favonia** [comment]
@cangiuli It's because equality types are written as `(= ty m n)` not `(= m n ty)`. But I ran into other issues that maybe @jonsterling can help:
```
Thm PathToFn(#l:lvl) : [
  (->
   [ty/a ty/b : (U #l kan)]
   [p : (path [_] (U #l kan) ty/a ty/b)]
   (-> ty/a ty/b))
] by [
  unfold Equiv;
  lam ty/a, ty/b, p, a.
    let eq0 : [(= (U #l kan) ty/a (@ p 0))] = auto.
    let eq1 : [(= (U #l kan) (@ p 1) ty/b)] = auto.
      fresh i -> `(coe 0~>1 [x] (@ p x) a);
      let eq2 : [(= (U #l kan) (@ p i) (@ p i))] = auto. auto; ?
].
```

**Comment by jonsterling** [comment]
@favonia You need to write `fresh i:dim ->...`; that doesn't solve the whole problem. Then I get a goal like:

```
   Goal #100.
     ty/a : (U #l kan)
     ty/b : (U #l kan)
     p : (path [_] (U #l kan) ty/a ty/b)
     a : ty/a
     eq0 : (= (U #l kan) ty/a (@ p 0))
     eq1 : (= (U #l kan) (@ p 1) ty/b)
     >> (@ p i) kan type at l (redprl)
```

Are you sure that we have the rules in place to solve this? I searched through the refiner and I did not find anything that would let me conclude that something is a type from the fact that it is a member of a universe. But maybe I missed it.

**Comment by favonia** [comment]
@jonsterling Ah, yes, I keep forgetting `i:dim`. Here is a proof without improving `StepEqTypeNeuByStruct`.
```
Thm PathToFn(#l:lvl) : [
  (->
   [ty/a ty/b : (U #l kan)]
   [p : (path [_] (U #l kan) ty/a ty/b)]
   (-> ty/a ty/b))
] by [
  unfold Equiv;
  lam ty/a, ty/b, p, a.
    let eq0 : [(= (U #l kan) ty/a (@ p 0))] = auto.
    let eq1 : [(= (U #l kan) (@ p 1) ty/b)] = auto.
      fresh i:dim -> `(coe 0~>1 [x] (@ p x) a);
      let eq2 : [(= (U #l kan) (@ p i) (@ p i))] =
        exact ax; refine eq/eq/ax; refine path/eq/app; auto.
      auto
].
```

**Comment by jonsterling** [comment]
@favonia This proof doesn't seem finished, at least on my machine. And the goal I get suggests that there is a bug!

```
  Goal #137.
    ty/a : (U #l kan)
    ty/b : (U #l kan)
    p : (path [_] (U #l kan) ty/a ty/b)
    a : ty/a
    eq0 : (= (U #l kan) ty/a (@ p 0))
    eq1 : (= (U #l kan) (@ p 1) ty/b)
    eq2 : (= (U #l kan) (@ p i) (@ p i))
    _0 : dim
    >> (@ p _0) coe type
```

Why is `i` not the same as `_0` in the above? Something is not right.

**Comment by jonsterling** [comment]
On the other hand, if I wrote the following, it works:

```
Thm PathToFn(#l:lvl) : [
  (->
   [ty/a ty/b : (U #l kan)]
   [p : (path [_] (U #l kan) ty/a ty/b)]
   (-> ty/a ty/b))
] by [
  unfold Equiv;
  lam ty/a, ty/b, p, a.
    let eq0 : [(= (U #l kan) ty/a (@ p 0))] = auto.
    let eq1 : [(= (U #l kan) (@ p 1) ty/b)] = auto.
      exact (coe 0~>1 [x] (@ p x) a);
      fresh i:dim -> auto;
      let eq2 : [(= (U #l kan) (@ p i) (@ p i))] =
        `ax; refine eq/eq/ax; refine path/eq/app; auto.

      auto
].
```

@favonia I bet you are on a version of RedPRL before I fixed #443. In any case, I think there is still a bug in the cut rule, since I shouldn't have been allowed to assert anything about `i` when `i` didn't appear in the context or as a meta.

**Comment by jonsterling** [comment]
@cangiuli Here's a cleaned up version of this proof that should work:

```
Thm PathToFn(#l:lvl) : [
  (->
   [ty/a ty/b : (U #l kan)]
   [p : (path [_] (U #l kan) ty/a ty/b)]
   (-> ty/a ty/b))
] by [
  unfold Equiv;
  lam ty/a, ty/b, p, a.
    `(coe 0~>1 [x] (@ p x) a);

    fresh i:dim -> auto;
      let eq0 : [ty/a = (@ p 0) in (U #l kan)] = auto.
      let eq1 : [(@ p 1) = ty/b in (U #l kan)] = auto.
      let eq2 : [(@ p i) in (U #l kan)] = refine path/eq/app; auto.
      auto
].
```

**Comment by favonia** [comment]
> @favonia This proof doesn't seem finished, at least on my machine. And the goal I get suggests that there is a bug!

Hmm. The scope of `i` seems to be broken on the branch on your machine, no matter what the branch is. I am currently on the `pushouts` branch, and I don't want to switch in the middle of implementing the crazy `Pushout.EqElim`.

**Comment by jonsterling** [comment]
@favonia Don't worry about it, I'll look into the issue 😄 

@cangiuli I'll write you a tactic to get rid of this crap

**Comment by jonsterling** [comment]
@cangiuli Here's an ultra-cleaned up version:

```
Tac ReflectUniv(#l:lvl, #k:knd, #t:tac) = [
  query goal <- concl.
  match goal {
    [a, b, k, l | #jdg{%a = %b type at %l with %[k:knd]} =>
      let aux : [%a = %b in (U #l #k)] = #t. auto
    ]
  }
].

Thm PathToFn(#l:lvl) : [
  (->
   [ty/a ty/b : (U #l kan)]
   [p : (path [_] (U #l kan) ty/a ty/b)]
   ty/a
   ty/b)
] by [
  lam ty/a, ty/b, p, a.
    `(coe 0~>1 [x] (@ p x) a);
    auto;

    (ReflectUniv #l kan #tac{auto});
    (ReflectUniv #l kan #tac{refine path/eq/app; auto})
].
```

**Comment by favonia** [comment]
I wonder what happened to `%a = %b in (U %l %[k:knd])`... which seems to fail in a mysterious way. And we should make the parser smart enough to parse `%k` at those locations as `%[k:knd]`.

**Comment by jonsterling** [comment]
@favonia Using the pattern variables in that location isn't what we want; for instance, in some cases `%l = omega`, and we're not going to be able to prove our auxiliary goal if we use that.

**Comment by favonia** [comment]
It is true that we are not able to prove it, but I feel provability should not affect pattern matching?

**Comment by favonia** [comment]
Sorry I misunderstood what you say. I see the problem of levels now. What happened to `(U #l %[k:knd])`, then?

**Comment by jonsterling** [comment]
@favonia Doing this leads to problems (that would be solved with better subtyping support).

**Comment by favonia** [comment]
> @favonia Doing this leads to problems (that would be solved with better subtyping support).

I thought `SUB_UNIVERSE` suffices. Could it be something about `KCONST`?

**Comment by favonia** [comment]
> @favonia This proof doesn't seem finished, at least on my machine. And the goal I get suggests that there is a bug!

Did you figure out the bug?

**Comment by favonia** [comment]
Essentially closed by #502. Now, only the type equality at the omega level can remain not internalized.
